
CREATE TABLE "user_role"(
                            id bigint NOT NULL generated by default as identity primary key,
                            role varchar (40) not null,
                            user_id bigint,
                           FOREIGN KEY (user_id) references "user"
);

alter table if exists user_role
    add constraint user_role_user_fk
        foreign key (user_id) references "user";